source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "6.1"

target "btc" do
    pod 'SDWebImage'
    pod 'AFNetworking'
    pod 'MBProgressHUD'
    pod 'CocoaLumberjack', '~> 2.0.0-beta4'
    pod 'SVPullToRefresh'
    pod 'SKSTableView', :git=> 'http://github.com/gokush/SKSTableView.git'
    pod 'ReactiveCocoa'
    pod 'JSONKit'
    pod 'CocoaSecurity'
end

target "btcTests" do
    pod 'AFNetworking'
    pod 'ReactiveCocoa'
    pod 'Specta'
    pod 'Expecta'
end